export const uiTextKo = {
  common: {
    loading: "로딩 중...",
    email: "이메일",
    password: "비밀번호",
    processing: "처리 중...",
  },
  landing: {
    headlineLine1: "학원 운영을 위한",
    headlineLine2: "통합 대시보드",
    description: "원장, 교사, 학부모, 학생이 하나의 데이터 모델에서 역할별 화면으로 함께 사용합니다.",
    login: "로그인",
    getStarted: "시작하기",
    features: [
      {
        title: "상담 일정 관리",
        description: "학부모가 상담을 신청하면 운영자가 승인하고 진행 상태를 한 흐름에서 관리합니다.",
      },
      {
        title: "학생 연결",
        description: "학부모는 링크 코드 기반 온보딩으로 학생과 안전하게 연결할 수 있습니다.",
      },
      {
        title: "공지사항",
        description: "중요한 학원 공지를 공통 피드로 전달합니다.",
      },
    ],
  },
  login: {
    title: "로그인",
    devModeDescription: "개발 모드에서는 이메일/비밀번호 로그인이 가능합니다.",
    productionDescription: "학원 계정으로 계속 진행하세요.",
    createAccountAndLoginButton: "회원가입 + 로그인",
    loginFailed: "로그인에 실패했습니다.",
    signUpLoginFailed: "회원가입/로그인에 실패했습니다.",
  },
  devLogin: {
    disabled: "개발 모드가 비활성화되어 있습니다.",
    title: "개발 로그인",
    description: "개발 전용 인증 도우미입니다.",
    loginSuccess: "로그인에 성공했습니다.",
    loginFailed: "로그인에 실패했습니다.",
    signUpLoginSuccess: "회원가입 + 로그인에 성공했습니다.",
    signUpLoginFailed: "회원가입/로그인에 실패했습니다.",
    sendResetEmail: "비밀번호 재설정 메일 보내기",
    resetEmailSent: "비밀번호 재설정 메일을 보냈습니다.",
    resetEmailFailed: "비밀번호 재설정 메일 발송에 실패했습니다.",
    logout: "로그아웃",
    logoutDone: "로그아웃되었습니다.",
    logoutFailed: "로그아웃에 실패했습니다.",
    signUpAndLogin: "회원가입 + 로그인",
    login: "로그인",
  },
  resetPassword: {
    preparing: "재설정 세션을 준비하는 중입니다...",
    checkingLink: "재설정 링크를 확인하는 중입니다...",
    processLinkFailed: "링크 처리에 실패했습니다",
    noActiveSession: "활성 세션이 없습니다. 이메일의 재설정 링크를 직접 열어 주세요.",
    enterNewPassword: "새 비밀번호를 입력해 주세요.",
    unknownError: "알 수 없는 오류",
    passwordMin: "비밀번호는 8자 이상이어야 합니다.",
    passwordMismatch: "비밀번호가 일치하지 않습니다.",
    updatedAndRedirect: "비밀번호가 변경되었습니다. 개발 로그인 화면으로 이동합니다...",
    updateFailed: "비밀번호 변경에 실패했습니다.",
    title: "비밀번호 재설정",
    newPassword: "새 비밀번호",
    confirmPassword: "비밀번호 확인",
    saving: "저장 중...",
    update: "비밀번호 변경",
  },
  onboardingRole: {
    loading: "로딩 중...",
    title: "역할 선택",
    description: "사용할 역할을 선택해 주세요.",
    saving: "저장 중...",
    sessionError: "세션 확인 실패",
    profileError: "프로필 확인 실패",
    roleButtons: [
      { role: "owner", label: "원장", description: "학생 정보와 학원 운영을 관리합니다." },
      { role: "teacher", label: "교사", description: "반 운영과 상담 업무를 관리합니다." },
      { role: "parent", label: "학부모", description: "학생을 연결하고 상담을 신청합니다." },
      { role: "student", label: "학생", description: "학생 프로필과 대시보드를 사용합니다." },
    ],
  },
  ownerDashboard: {
    title: "원장 대시보드",
    description: "핵심 관리 페이지로 빠르게 이동합니다.",
    menus: [
      { href: "/owner/students", title: "학생 관리", description: "학생 프로필을 조회하고 수정합니다." },
      { href: "/owner/consult/requests", title: "상담 요청", description: "상담 요청을 승인하고 관리합니다." },
      { href: "/owner/consult/calendar", title: "상담 캘린더", description: "날짜와 상태별 일정을 확인합니다." },
      { href: "/owner/generate-link-code", title: "연결 코드", description: "학부모-학생 연결 코드를 발급합니다." },
      { href: "/owner/announcements/new", title: "공지 작성", description: "새 공지를 작성하고 게시합니다." },
    ],
  },
  teacherDashboard: {
    title: "교사 대시보드",
    description: "수업 운영 기능으로 빠르게 이동합니다.",
    menus: [
      { href: "/owner/students", title: "학생 관리", description: "학생 프로필과 반 정보를 확인합니다." },
      { href: "/owner/consult/requests", title: "상담 요청", description: "학부모 상담 요청을 처리합니다." },
      { href: "/owner/consult/calendar", title: "상담 캘린더", description: "확정된 일정을 날짜별로 확인합니다." },
      { href: "/announcements", title: "공지사항", description: "최신 학원 공지를 확인합니다." },
    ],
  },
  parentDashboard: {
    title: "학부모 대시보드",
    description: "상담 및 학생 연결 기능을 이용할 수 있습니다.",
    menus: [
      { href: "/consult/request", title: "상담 신청", description: "시간을 선택해 상담을 신청합니다." },
      { href: "/parent/students", title: "내 학생", description: "연결된 학생을 관리합니다." },
      { href: "/link-student", title: "학생 연결", description: "링크 코드를 사용해 학생을 연결합니다." },
      { href: "/announcements", title: "공지사항", description: "학원 공지를 확인합니다." },
    ],
  },
  studentDashboard: {
    title: "학생 대시보드",
    description: "상태 카드와 공지사항을 확인합니다.",
    placeholders: [
      { title: "학습", description: "학습 진도와 상태 요약입니다." },
      { title: "미션", description: "과제와 복습 체크리스트입니다." },
      { title: "출결", description: "최근 출결 기록입니다." },
    ],
    comingSoon: "준비 중",
    quickLinks: "바로가기",
    menus: [
      { href: "/student/setup", label: "프로필 설정" },
      { href: "/announcements", label: "전체 공지" },
    ],
  },
  parentStudents: {
    elementary: "초등",
    middle: "중등",
    high: "고등",
    unknown: "미입력",
    loadStudentsFailed: "학생 목록 조회 실패",
    sessionError: "세션 확인 실패",
    roleCheckFailed: "권한 확인 실패",
    unlinkConfirmPrefix: "연결을 해제할까요?",
    unknownStudent: "이름 없음",
    unlinkFailed: "연결 해제 실패",
    title: "내 학생",
    linkStudent: "학생 연결",
    noLinkedStudents: "아직 연결된 학생이 없습니다.",
    relation: "관계",
    linkedAt: "연결일시",
    unlinking: "해제 중...",
    unlink: "연결 해제",
  },
  ownerConsultCalendar: {
    sessionCheckFailed: "세션 확인 실패",
    roleCheckFailed: "권한 확인 실패",
    loading: "로딩 중...",
    title: "상담 캘린더",
    unavailable: "캘린더 모듈은 현재 일시적으로 사용할 수 없습니다.",
    goToRequests: "상담 요청 목록으로 이동",
  },
} as const;
