export const ANNOUNCEMENT_TEXT = {
  title: "알리미함",
  subtitle: "학원 알리미와 안내를 확인합니다.",
  ownerOnlyTitle: "원장 전용 관리 페이지가 있습니다.",
  ownerOnlyDescription: "이 페이지는 학생·학부모용 알리미함입니다. 원장 알리미 관리는 전용 페이지를 이용해 주세요.",
  ownerMoveManage: "원장 알리미 관리로 이동",
  ownerMoveNew: "새 알리미 작성",
  empty: "등록된 알리미가 없습니다.",
  emptySearch: "검색 결과가 없습니다.",
  recent: "최근 알리미",
  attachments: "첨부파일",
  searchPlaceholder: "제목/내용 검색",
  summaryUnread: "미확인",
  summaryStarred: "별표",
  summaryWithAttachments: "첨부",
  loading: "로딩 중...",
  filterAll: "전체",
  filterUnread: "읽지 않음",
  tabAll: "전체",
  tabUnread: "읽지 않음",
  tabUnacknowledged: "확인 필요",
  filterStarred: "별표",
  unreadCountPrefix: "미확인",
  unreadCountSuffix: "건",
  emptyUnread: "읽지 않은 알리미가 없습니다.",
  read: "읽음",
  unread: "읽지 않음",
  loadErrorFallback: "알리미를 불러오지 못했습니다.",
  attachmentNone: "첨부파일이 없습니다.",
  attachmentDownloadFail: "첨부파일 다운로드에 실패했습니다.",
  sessionCheckFailed: "세션 확인에 실패했습니다.",
  filterWithAttachmentsOnly: "첨부 있음만",
  sortLatest: "최신순",
  sortUnreadFirst: "미확인 우선",
  sortLabel: "정렬",
  unreadDotLabel: "미확인",
  attachmentIconLabel: "첨부",
  filterStarredOnly: "별표만",
  targetLabel: "대상",
  targetUnknown: "정보 없음",
  targetAll: "전체",
  targetSchoolLevel: "학교급",
  targetGrade: "학년",
  targetClass: "반",
  targetStudent: "개별",
  schoolLevelElem: "초등",
  schoolLevelMid: "중등",
  schoolLevelHigh: "고등",
  gradeSuffix: "학년",
  classSuffix: "반",
  audienceLabel: "수신",
  categoryLabel: "유형",
  starAdd: "별표 추가",
  starRemove: "별표 해제",
  audienceAll: "전체",
  audienceStudent: "학생",
  audienceParent: "학부모",
  detailInvalidPath: "잘못된 알리미 경로입니다.",
  detailLoadFailedPrefix: "알리미 조회 실패",
  detailNotFound: "요청한 알리미를 찾을 수 없습니다.",
  deleteAction: "삭제",
  deleting: "삭제 중...",
  deleteConfirm: "이 알리미를 삭제 처리하시겠습니까?",
  deleteFailed: "알리미 삭제 처리에 실패했습니다.",
  deletedNotice: "삭제된 알리미입니다.",
  moveToList: "알리미함으로",
  ackButton: "확인",
  ackDoneBadge: "확인 완료",
  processing: "처리 중...",
} as const;
