export const AUTH_TEXT = {
  loginTitle: "MVS 로그인",
  loginSubtitle: "학생, 학부모, 원장/교사가 각자 계정으로 로그인해요.",
  emailLabel: "이메일",
  passwordLabel: "비밀번호",
  loginButton: "로그인",
  signUpButton: "계정 만들기",
  resetPasswordLink: "비밀번호를 잊으셨나요?",
  devOnlyDescription: "개발 전용 로그인 화면입니다.",
  productionDescription: "운영 로그인 화면으로 이동",
  loginFailed: "로그인에 실패했습니다.",
  signUpLoginFailed: "회원가입 처리에 실패했습니다.",
  resetEmailSent: "비밀번호 재설정 메일을 보냈습니다.",
  resetEmailFailed: "비밀번호 재설정 메일 전송에 실패했습니다.",
  processing: "처리 중...",

  roleStudent: "학생",
  roleParent: "학부모",
  roleStaff: "원장/교사",
  roleHintStudent: "학생 계정으로 로그인합니다.",
  roleHintParent: "학부모 계정으로 로그인합니다. 자녀 연결은 로그인 후 진행해요.",
  roleHintStaff: "원장/교사 계정으로 로그인합니다.",

  signupTitle: "MVS 계정 만들기",
  signupSubtitle: "학생 또는 학부모 계정을 만들어 서비스를 시작하세요.",
  signupStudentOnlyTitle: "학생 계정 정보",
  signupParentTitle: "학부모 계정 정보",
  signupParentGuideTitle: "학부모도 독립 계정으로 시작해요.",
  signupParentGuideDescription: "학부모 계정을 만든 뒤 자녀 연결 코드 또는 QR로 최초 1회 연결을 진행해 주세요.",
  signupParentGuideButton: "자녀 연결하기",
  nameLabel: "이름",
  schoolLevelLabel: "학교급",
  gradeLabel: "학년",
  classLabelOptional: "반(선택)",
  signupSubmitButton: "가입 완료",
  signupSuccessStudent: "가입이 완료되었습니다. 관심 분야 선택 단계로 이동합니다.",
  signupSuccessParent: "학부모 계정이 생성되었습니다. 자녀 연결을 이어서 진행해 주세요.",
  backToLogin: "이미 계정이 있어요",
  invalidInput: "필수 정보를 입력해 주세요.",
  selectPlaceholder: "선택",
  parentLoginPromptTitle: "학부모 계정이 필요해요",
  parentLoginPromptDescription: "자녀 연결은 학부모 로그인 또는 계정 만들기 후 이어서 진행할 수 있어요.",
} as const;
