export const NOTICES_TEXT = {
  sectionHeader: "최근 알리미/안내",
  feedTitle: "알리미 목록",
  moveToAll: "전체 알리미 보기",
  allLabel: "전체 알리미",
  ownerWriteLabel: "알리미 작성",
  loading: "로딩 중...",
  loadFailed: "알리미 로딩에 실패했습니다.",
  loadFailedApprovalRequired: "승인 후 이용 가능합니다.",
  loadFailedRetry: "알리미를 불러오지 못했습니다. 새로고침 해주세요.",
  empty: "등록된 알리미가 없습니다.",
  unreadBadge: "미읽음",
  unreadCountLabel: "미읽음",
  unreadCountSuffix: "건",
  tabAll: "전체",
  tabGroup: "내 그룹",
  tabPersonal: "개인",
  filterUnreadOnly: "미읽음만",
  filterWithAttachmentOnly: "첨부 있음만",
  filterStarredOnly: "별표만",
  attachmentMark: "첨부",
  starAdd: "별표 추가",
  starRemove: "별표 해제",
  ownerHomeTitle: "원장 홈",
  ownerSubtitle: "상담 운영과 학원 알리미 관리를 한 화면에서 진행할 수 있습니다.",
  ownerSummaryTitle: "알리미",
  ownerSummaryDescription: "중요 알리미 노출 우선순위를 반영한 운영 알림 요약입니다.",
  ownerWriteDescription: "중요 알리미를 작성해 전체 사용자에게 전달합니다.",
  parentSubtitle: "자녀 연결, 상담 요청, 알리미 확인을 한 화면에서 이용할 수 있습니다.",
  parentSummaryTitle: "알리미",
  parentSummaryDescription: "중요 알리미 우선 노출을 반영한 요약 카드입니다.",
  parentAllDescription: "학원 주요 알리미와 일정 안내를 빠르게 확인합니다.",
  deleteAction: "삭제",
  deleting: "삭제 중...",
  deleteConfirm: "이 알리미를 삭제 처리하시겠습니까?",
  deleteFailed: "알리미 삭제 처리에 실패했습니다.",
} as const;
