export const OWNER_DASHBOARD_TEXT = {
  ownerHomeTitle: "원장 홈",
  ownerHomeSubtitle: "상담 운영과 학원 알리미 관리를 한 화면에서 진행할 수 있습니다.",
  todayPendingTitle: "오늘 승인 대기",
  todayPendingDescription: "신규 상담 요청 집계를 빠르게 확인하도록 준비 중입니다.",
  todayConfirmedTitle: "오늘 확정",
  todayConfirmedDescription: "확정된 상담 일정을 날짜/시간 기준으로 보여주는 요약 카드입니다.",
  blockedSlotsTitle: "차단 슬롯",
  blockedSlotsDescription: "운영 불가 슬롯을 관리하기 위한 요약 카드입니다.",
  noticesSummaryTitle: "알리미",
  noticesSummaryDescription: "중요 알리미 노출 우선순위를 반영한 운영 알림 요약입니다.",
  quickActionsTitle: "빠른 실행",
  quickActionsDescription: "자주 사용하는 업무 메뉴로 바로 이동합니다.",
  menuStudentsTitle: "학생 관리",
  menuStudentsDescription: "학생 정보를 조회하고 필요한 수정 업무를 빠르게 처리합니다.",
  menuConsultRequestsTitle: "상담 요청",
  menuConsultRequestsDescription: "보호자 상담 요청을 확인하고 상태를 처리합니다.",
  menuConsultCalendarTitle: "상담 캘린더",
  menuConsultCalendarDescription: "날짜별 상담 현황과 차단 상태를 한 번에 관리합니다.",
  noticesSectionTitle: "최근 알리미",
  badgeReady: "준비 중",
  badgeActive: "운영 중",
} as const;
