export const OWNER_ANNOUNCEMENTS_TEXT = {
  title: "원장 알리미 관리",
  subtitle: "보낸 알림을 확인하고 삭제나 복구를 관리합니다.",
  tabActive: "전체",
  tabTrash: "휴지통",
  searchPlaceholder: "제목/내용 검색",
  filterAudienceLabel: "수신 대상",
  filterPeriodLabel: "기간",
  filterWithAttachmentsOnly: "첨부만 보기",
  periodAll: "전체",
  periodToday: "오늘",
  period7Days: "7일",
  period30Days: "30일",
  audienceAll: "전체",
  audienceStudent: "학생",
  audienceParent: "학부모",
  categoryLabel: "유형",
  targetLabel: "대상",
  recipientsLabel: "수신",
  ackLabel: "확인",
  unacknowledgedLabel: "미확인",
  scheduledLabel: "예약 발송",
  scheduledPending: "예약 대기",
  directLabel: "직접 지정",
  resendUnacknowledged: "미확인만 재알림",
  resendDone: "미확인 대상에게 다시 알렸습니다.",
  resendEmpty: "미확인 수신자가 없습니다.",
  resendUnsupported: "재알림 기능을 현재 환경에서 사용할 수 없습니다.",
  templatePrefix: "[재알림] ",
  attachmentsLabel: "첨부",
  actionDelete: "삭제",
  actionRestore: "복구",
  deleting: "처리 중...",
  resending: "재알림 중...",
  confirmDelete: "이 알림을 휴지통으로 이동할까요?",
  confirmRestore: "이 알림을 복구할까요?",
  loading: "불러오는 중...",
  emptyActive: "등록된 알림이 없습니다.",
  emptyTrash: "휴지통이 비어 있습니다.",
  accessDenied: "원장만 접근할 수 있습니다.",
  loadFailed: "알리미 목록을 불러오는 중 문제가 발생했습니다.",
  updateFailed: "알리미 상태를 변경하는 중 문제가 발생했습니다.",
  updateDone: "알리미 상태를 변경했습니다.",
} as const;
