export const OWNER_ANNOUNCEMENT_NEW_TEXT = {
  pageTitle: "알리미 등록",
  pageDescription: "학생·학부모에게 보낼 알림을 작성합니다.",
  goToList: "목록으로",
  contentCardTitle: "알림 내용",
  contentCardDescription: "제목과 내용을 작성하고 필요한 파일을 첨부합니다.",
  targetCardTitle: "수신 대상",
  targetCardDescription: "대상 범위를 선택해 학생과 학부모에게 알림을 보냅니다.",
  summaryCardTitle: "발송 요약",
  summaryCardDescription: "선택한 대상과 예상 수신 인원을 확인한 뒤 발송합니다.",
  submit: "알리미 발송",
  submitScheduled: "예약 등록",
  submitting: "발송 중...",
  successRegistered: "알리미가 등록되었습니다.",
  successScheduled: "알리미 예약이 등록되었습니다. 설정한 시간에 자동 발송됩니다.",
  titleLabel: "제목",
  titlePlaceholder: "예: 3월 학부모 상담 일정 안내",
  bodyLabel: "내용",
  bodyPlaceholder: "보낼 내용을 입력해 주세요.",
  audienceRoleLabel: "수신 대상",
  targetScopeLabel: "대상 범위",
  schoolLevelLabel: "학교급",
  gradeLabel: "학년",
  classLabel: "반",
  studentLabel: "개별 학생",
  schoolLevelPlaceholder: "학교급 선택",
  gradePlaceholder: "학년 선택",
  classPlaceholder: "예: 1",
  requiresAckLabel: "확인 필요 (ACK)",
  requiresAckHelp: "확인이 필요한 알림에 사용합니다.",
  attachmentLabel: "첨부파일",
  attachmentHelp: "파일당 최대 5MB까지 첨부할 수 있습니다.",
  attachmentSelectedEmpty: "선택한 첨부파일이 없습니다.",
  attachmentRemove: "제거",
  attachmentInvalid: "첨부파일 형식 또는 용량을 다시 확인해 주세요.",
  validationTitleBody: "제목과 내용을 입력해 주세요.",
  validationTarget: "대상 조건을 다시 확인해 주세요.",
  validationScheduledAt: "예약 발송 시간을 미래 시간으로 설정해 주세요.",
  deliveryModeLabel: "발송 시점",
  deliveryModeNow: "즉시 발송",
  deliveryModeScheduled: "예약 발송",
  scheduledAtLabel: "발송 일시 (KST)",
  scheduledAtHelp: "설정한 시각이 지나면 자동으로 발송됩니다 (최대 15분 지연).",
  loadFailed: "알리미 화면을 불러오는 중 문제가 발생했습니다.",
  loadStudentsFailed: "학생 목록을 불러오는 중 문제가 발생했습니다.",
  submitErrorFallback: "알리미 등록 중 문제가 발생했습니다.",
  summaryAudienceLabel: "수신 대상",
  summaryScopeLabel: "대상 범위",
  summaryRecipientCountLabel: "예상 수신 인원",
  summaryUnknown: "-",
  summaryStudentCountSuffix: "명",
} as const;
