export const PARENT_LINK_ONBOARDING_TEXT = {
  title: "자녀 연결하기",
  subtitle: "연결코드를 입력하면 자녀와 학부모 계정을 연결할 수 있어요.",
  codeLabel: "연결코드",
  codePlaceholder: "예: 8자리 코드",
  relationLabel: "관계(선택)",
  relationGuardian: "보호자",
  relationMother: "어머니",
  relationFather: "아버지",
  submit: "연결하기",
  submitting: "연결 중...",
  success: "연결 완료",
  helpTitle: "연결코드를 모르겠어요",
  helpDescription: "학원 또는 학생에게 연결코드를 문의해 주세요.",
  loginRequired: "로그인이 필요합니다.",
  roleDenied: "학부모 계정만 접근할 수 있습니다.",
  codeTooShort: "연결코드를 확인해 주세요.",
  failedPrefix: "연결 실패",
} as const;
