export const PARENT_HOME_TEXT = {
  title: "학부모 홈",
  subtitle: "자녀와의 연결 및 주요 안내를 빠르게 확인할 수 있는 홈 화면입니다.",
  heroTitle: "상담이 필요하신가요?",
  heroSubtitle: "자녀 학습을 확인하고, 필요할 때 바로 상담을 예약하세요.",
  ctaTitle: "상담 예약",
  ctaDescription: "원하는 시간대로 상담을 요청할 수 있어요.",
  ctaButton: "상담 예약하기",
  ctaSecondaryButton: "알리미함 보기",
  unreadBadgePrefix: "미읽음",
  linkRequiredTitle: "자녀 연결이 필요해요",
  linkRequiredDescription: "연결코드를 입력하면 상담과 알리미를 바로 사용할 수 있어요.",
  linkRequiredAction: "연결코드 입력하기",
  nextConsultationTitle: "다음 상담",
  nextConsultationEmpty: "예정된 상담 없음",
  nextConsultationView: "상담 확인/예약하기",
  nextConsultationStudentFallback: "학생",
  nextConsultationMetaFallback: "정보 없음",
  nextConsultationSchoolLevelElem: "초",
  nextConsultationSchoolLevelMid: "중",
  nextConsultationSchoolLevelHigh: "고",
  nextConsultationGradeSuffix: "학년",
  noticesTitle: "최근 알리미",
  noticesMore: "전체 알리미",
  summaryTitle: "예약 상태",
  summaryPending: "승인 대기",
  summaryConfirmed: "확정",
  summaryToday: "오늘",
  comingSoon: "준비 중",
} as const;
