export const STUDENT_NOTICE_TEXT = {
  sectionHeader: "최근 알리미/안내",
  sectionDescription: "학습에 필요한 최신 안내를 확인하세요.",
  feedTitle: "알리미 목록",
  moveToAnnouncements: "전체 알리미로 이동",
  more: "전체 보기",
  loading: "로딩 중...",
  loadFailed: "알리미 로딩에 실패했습니다.",
  empty: "등록된 알리미가 없습니다.",
  unreadPrefix: "미읽음 ",
  unreadSuffix: "건",
  tabAll: "전체",
  tabGradeClass: "내 학년·반",
  tabPersonal: "개인",
  filterUnreadOnly: "미읽음만",
  filterWithAttachmentOnly: "첨부 있음만",
} as const;
