export const STUDENT_HOME_TEXT = {
  title: "학생 홈",
  subtitle: "오늘의 학습 흐름과 알리미를 한 화면에서 확인하세요.",
  heroGreeting: (name: string) => `안녕, ${name} 🌟`,
  heroTitle: "오늘도 안정적인 학습 루틴을 시작해요",
  heroMessage: "오늘의 학습을 시작해볼까요?",
  defaultName: "학생",
  heroDeck: [
    {
      emoji: "🌟",
      title: "오늘의 학습을 가볍게 시작해요",
      subtitle: "작은 시작이 쌓이면 큰 성장으로 이어집니다.",
    },
    {
      emoji: "🚀",
      title: "집중 모드로 한 단계 더 올라가요",
      subtitle: "오늘의 할 일을 차근차근 완료해 보세요.",
    },
    {
      emoji: "📘",
      title: "기초를 단단하게 다지는 날이에요",
      subtitle: "복습과 정리를 중심으로 학습 흐름을 만들어요.",
    },
    {
      emoji: "🎯",
      title: "핵심 목표를 정확히 겨냥해요",
      subtitle: "중요한 항목부터 확인하고 우선순위를 잡아보세요.",
    },
    {
      emoji: "✨",
      title: "오늘의 루틴을 반짝이게 완성해요",
      subtitle: "알리미와 미션을 확인하고 리듬을 이어가요.",
    },
  ],
  todaySectionTitle: "오늘 해야 할 것",
  todaySectionDescription: "지금 바로 확인하면 좋은 핵심 항목입니다.",
  todayStudyTitle: "오늘의 학습",
  todayStudyDescription: "학습 진행 상태와 다음 학습 단계 안내가 곧 제공됩니다.",
  todayMissionTitle: "오늘의 미션",
  todayMissionDescription: "오늘 수행할 미션과 체크 흐름을 준비 중입니다.",
  todayNoticeTitle: "새로운 알리미",
  todayNoticeDescription: "미읽음 알리미를 먼저 확인해 중요한 안내를 놓치지 않도록 도와드립니다.",
  todayStudyEmoji: "📚",
  todayMissionEmoji: "🧩",
  todayNoticeEmoji: "🔔",
  unreadBadgePrefix: "미읽음",
  growthSectionTitle: "나의 성장",
  growthSectionDescription: "학습과 참여 흐름을 한눈에 보는 성장 지표입니다.",
  growthCards: [
    {
      title: "이번 주 학습 시간",
      value: "0h",
      description: "학습 시간 집계 연동을 준비 중입니다.",
      emoji: "⏱️",
    },
    {
      title: "완료한 미션",
      value: "0",
      description: "미션 완료 데이터 연동을 준비 중입니다.",
      emoji: "✅",
    },
    {
      title: "연속 출석일",
      value: "0",
      description: "출석 리듬 추적 기능을 준비 중입니다.",
      emoji: "🔥",
    },
  ],
  quickLinksTitle: "빠른 실행",
  quickLinksDescription: "자주 쓰는 메뉴를 바로 이동할 수 있습니다.",
  quickLinks: [
    {
      href: "/student/setup",
      label: "프로필 설정",
      description: "학습 준비를 위한 기본 정보를 최신 상태로 유지합니다.",
    },
    {
      href: "/announcements",
      label: "전체 알리미",
      description: "학원 주요 안내와 일정을 빠르게 확인합니다.",
    },
  ],
  noticeSectionTitle: "알리미",
  noticeSectionDescription: "최신 안내를 확인하고 필요한 항목을 바로 확인하세요.",
  noticeFeedTitle: "최근 알리미",
  noticeMoveToAll: "전체 알리미로 이동",
  comingSoon: "준비 중",
} as const;

