export const studentMathCopy = {
  title: "수학 탐구 미션",
  subtitle: "학년, 단원, 관심 주제에 따라 수학 미션을 골라보세요.",
  heroTitle: "수학 탐구 미션",
  heroDescription: "새로 열린 단원과 추천 미션을 바탕으로 지금 맞는 학습 경로를 찾아보세요.",
  overviewLabel: "오늘의 학습",
  levelLabel: "현재 레벨",
  totalXpLabel: "총 XP",
  nextXpLabel: "다음 레벨까지",
  todayGoalLabel: "오늘 목표: 1개 완료",
  weeklyGoalLabel: "이번 주 목표: 5개 완료",
  achievedLabel: "달성",
  todayCountLabel: "오늘 완료",
  weeklyCountLabel: "이번 주 완료",
  startMissionLabel: "미션 시작하기",
  filtersTitle: "빠른 탐색",
  filters: {
    all: "전체",
    grade: "학년별",
    fresh: "새 단원",
    career: "직업 연결",
    popular: "인기 미션",
    recent: "최근 학습",
  },
  gradeSectionTitle: "학년별 단원 탐색",
  gradeSectionDescription: "선택한 학년 기준으로 단원과 연결된 미션을 살펴보세요.",
  currentGradeLabel: "현재 표시 학년",
  freshSectionTitle: "새로 열린 단원",
  freshSectionDescription: "최근 미션이 추가된 단원을 먼저 탐색해 보세요.",
  interestSectionTitle: "관심 주제로 찾기",
  interestSectionDescription: "좋아하는 주제를 고르면 연결된 수학 미션을 빠르게 볼 수 있어요.",
  interestTopics: ["아이돌", "게임", "스포츠", "여행", "패션", "학교생활", "로봇/AI", "동물"] as const,
  careerSectionTitle: "실제 직업에서 쓰이는 수학",
  careerSectionDescription: "직업과 연결된 실제 상황 미션을 중심으로 수학을 만나보세요.",
  careerBadge: "직업 연결",
  newBadge: "NEW",
  unitExploreLabel: "단원 보기",
  missionStartLabel: "시작하기",
  missionCountLabel: "미션",
  unitDescriptionFallback: "실생활 상황과 연결된 탐구 미션을 확인해 보세요.",
  loading: "불러오는 중...",
  loadError: "수학 홈 화면을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
  noUnits: "해당 학년에는 아직 공개된 단원이 없어요.",
  noFreshUnits: "새로 열린 단원을 준비 중입니다.",
  noInterestMissions: "선택한 관심 주제에 맞는 미션을 더 준비 중입니다.",
  noCareerMissions: "직업 연결 미션을 준비 중입니다.",
  noFilteredCareerMissions: "선택한 분야에 맞는 직업 연결 미션을 더 준비 중입니다.",
  resumeTitle: "최근 이어서 하기",
  resumeDescription: "진행 중이거나 최근 본 미션을 다시 이어갈 수 있어요.",
  resumeEmpty: "이어서 할 미션이 없어요.",
  weakTitle: "조금 더 연습하면 좋은 개념",
  weakDescription: "최근 풀이를 바탕으로 다시 보면 좋은 개념을 골라두었어요.",
  weakEmpty: "아직 분석할 풀이 기록이 충분하지 않아요.",
  weakBadge: "복습 추천",
  replayTitle: "다시 보면 좋아요",
  replayDescription: "이전에 풀었던 미션 중 다시 확인하면 좋은 내용을 모아두었어요.",
  replayEmpty: "다시 추천할 미션이 아직 없어요.",
  nextTitle: "다음으로 추천해요",
  nextDescription: "같은 개념 흐름에서 다음으로 보기 좋은 미션을 골라두었어요.",
  nextEmpty: "지금은 새로 추천할 미션이 없어요.",
  popularTitle: "인기 미션",
  popularDescription: "자주 다시 보는 추천 미션을 모아두었어요.",
  recentMissionsTitle: "최근 학습",
  recentMissionsDescription: "최근 완료한 미션을 다시 보거나 복습 흐름으로 이어갈 수 있어요.",
  recentMissionsEmpty: "최근 완료한 미션이 아직 없어요.",
  difficultyLabel: "난이도",
  estimatedLabel: "예상",
  minutesLabel: "분",
} as const;
